### ISSUE TITLE
darknet.py doesnt work. cant find darknet.so

### ISSUE THREAD

**Issue by hfmsite** [pjreddie/darknet#1182]
my system:
ryzen 5 -2600
gtx 1080

ubuntu 18.04
cuda 10 
opencv 3.4.3

fresh clone of the git - and compile.
there isn't darknet.so file anyware
(even try to delete the folder and start again from scrach)

the error message:
`Traceback (most recent call last):
  File "darknet.py", line 122, in <module>
    lib = CDLL("./darknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./darknet.so: cannot open shared object file: No such file or directory`

thank's a lot for the great project

**Comment by hfmsite** [comment]
wrong reposetory
