### ISSUE TITLE
segmentation fault(core dumped)

### ISSUE THREAD

**Issue by likeyu21** [pjreddie/darknet#1228]
when I run the demo with my trained yolov3 model, the camera can be open, but the problem 'segmentation fault' occurs as long as the camera detects objects . I don't know why it happen. Please help me.

**Comment by pdewilde** [comment]
I got a segmentation fault when trying to train a new rnn with the command  `./darknet rnn train cfg/rnn.train.cfg -file myfile.txt`

I tried both in an ubuntu and centos environment. It happened in different places each time.

Before I stripped non-ascii charcters (on WSL ubuntu)
```
#0  0x000000000044f1f3 in fill_cpu ()
#1  0x000000000046a5dc in forward_rnn_layer ()
#2  0x000000000045a8da in forward_network ()
#3  0x000000000045abe2 in train_network_datum ()
#4  0x000000000040c6b3 in train_char_rnn ()
#5  0x00000000004020ea in main ()```

On the centos after stripping non-ascii characters

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff756736c in fseek () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff756736c in fseek () from /lib64/libc.so.6
#1  0x000000000041f2d2 in read_file ()
#2  0x000000000040cd88 in train_char_rnn ()
#3  0x0000000000402a79 in main ()
```

**Comment by jordanranson** [comment]
> I got a segmentation fault when trying to train a new rnn with the command `./darknet rnn train cfg/rnn.train.cfg -file myfile.txt`
> 
> I tried both in an ubuntu and centos environment. It happened in different places each time.
> 
> Before I stripped non-ascii charcters (on WSL ubuntu)
> 
> ```
> #0  0x000000000044f1f3 in fill_cpu ()
> #1  0x000000000046a5dc in forward_rnn_layer ()
> #2  0x000000000045a8da in forward_network ()
> #3  0x000000000045abe2 in train_network_datum ()
> #4  0x000000000040c6b3 in train_char_rnn ()
> #5  0x00000000004020ea in main ()
> ```
> On the centos after stripping non-ascii characters
> 
> ```
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff756736c in fseek () from /lib64/libc.so.6
> (gdb) bt
> #0  0x00007ffff756736c in fseek () from /lib64/libc.so.6
> #1  0x000000000041f2d2 in read_file ()
> #2  0x000000000040cd88 in train_char_rnn ()
> #3  0x0000000000402a79 in main ()
> ```

I'm having a similar issue: https://github.com/pjreddie/darknet/issues/1227

**Comment by YunYang1994** [comment]
https://github.com/YunYang1994/tensorflow-yolov3 hope it helps you
