### ISSUE TITLE
Real time webcam not working darknet.py

### ISSUE THREAD

**Issue by Flock1** [pjreddie/darknet#1384]
HI,

I am trying to run darknet on TX2 and the C++ implementation seems to working fine. I want to implement the python version. I am able to run it on images but when I try to use webcam, I get thew following error:

```
Traceback (most recent call last):
  File "darknet.py", line 168, in <module>
    r = detect(net, meta, img)
  File "darknet.py", line 131, in detect
    im = load_image(image, 0, 0)
ctypes.ArgumentError: argument 1: <type 'exceptions.TypeError'>: wrong type
```

The code I've written is:

```
    net = load_net("/home/darknet/cfg/yolov3-tiny.cfg", "/home/darknet/yolov3-tiny.weights", 0)
    meta = load_meta("/home/darknet/cfg/coco.data")
    cap = cv2.VideoCapture(1)
    ret, img = cap.read()
    while(ret):
        r = detect(net, meta, img)
        print(r)
```

I have various steps like #241 but nothing seems to work. Can someone help me?

**Comment by MMaxV** [comment]
It's because detect method take the path to image file, to make detection. OpenCV method read() returns image as numpy array. That's why you have an error. If you want to use detect method with webcam change line:  im = load_image(image, 0, 0) on line: im = nparray_to_image(image) in detect method in darknet.py.
