### ISSUE TITLE
请问darknet的python接口更新后，无make_boxes...这几个函数，怎么解决的?

### ISSUE THREAD

**Issue by jiagh2010** [pjreddie/darknet#1565]

**Comment by jiagh2010** [comment]
@pjreddie pjreddie

**Comment by jiagh2010** [comment]
@pjreddie   new   version  error ！！when using opencv！！！

**Comment by jiagh2010** [comment]
Loading weights from army/my_yolov3_final.weights...Done!
Traceback (most recent call last):
  File "detector-scipy-opencv.py", line 47, in <module>
    r = detect2(net, meta, im)
  File "detector-scipy-opencv.py", line 20, in detect2
    boxes = dn.make_boxes(net)
AttributeError: 'module' object has no attribute 'make_boxes'
Loading weights from army/my_yolov3_final.weights...Done!
Traceback (most recent call last):
  File "detector-scipy-opencv.py", line 47, in <module>
    r = detect2(net, meta, im)
  File "detector-scipy-opencv.py", line 20, in detect2
    boxes = dn.make_boxes(net)
AttributeError: 'module' object has no attribute 'make_boxes'
