### ISSUE TITLE
getting error while importing darknet because of libdarknet.so

### ISSUE THREAD

**Issue by VishvajeetRamanuj** [pjreddie/darknet#1655]
when i try to compile darknet with opencv it shown me error which is already open issue on github. So i make darknet without opencv. It generated libdarknet.so file. but when i try to import darknet it shown me bellow error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vishvajeet/Vishvajeet/Programming/darknet/darknet.py", line 128, in <module>
    copy_image_from_bytes = lib.copy_image_from_bytes
  File "/home/vishvajeet/anaconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/vishvajeet/anaconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./libdarknet.so: undefined symbol: copy_image_from_bytes

Configuration I am using:
ubuntu : 18.04 LTS
opencv : 3.4.2

**Comment by 869250498** [comment]
I meet the same mistake.

**Comment by georgesmarkus** [comment]
same error

**Comment by HaoRecog** [comment]
same  error      why????

**Comment by mushroompyq** [comment]
I have the same mistake.Did anyone resolve it？Thanks. @869250498 @VishvajeetRamanuj

**Comment by pablus09** [comment]
Same error...

**Comment by Aaron0932217077** [comment]
Same error

**Comment by imohamadhoseins** [comment]
same error, no solution?

**Comment by nauyan** [comment]
@VishvajeetRamanuj @869250498 @georgesmarkus @HaoRecog @pablus09 @Aaron0932217077 @imohamadhoseins have you guys been able to fix this issue?

**Comment by oukohou** [comment]
exactly same error，any update?

**Comment by nauyan** [comment]
@oukohou  yes I built darknet using @AlexeyAB  repo and didn't run into this error.

Repo: https://github.com/AlexeyAB/darknet

**Comment by oukohou** [comment]
@nauyan That helped, Thanks!
