### ISSUE TITLE
Segmentation fault when train tiny-yolo

### ISSUE THREAD

**Issue by Sander-houqi** [pjreddie/darknet#178]
Hi:

when I use ./darknet detector train cfg/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights to train my
own datasets,it cause Segmentation fault,but I dont't how to fix it .

here is gdb results by use command:  gdb --args ./darknet detector train cfg/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights

[New Thread 0x7fffe7887700 (LWP 18472)]
[New Thread 0x7fffe9719700 (LWP 18473)]
[New Thread 0x7fffe9f1a700 (LWP 18474)]
[New Thread 0x7fffeaf1c700 (LWP 18475)]
[New Thread 0x7fffea71b700 (LWP 18476)]
[New Thread 0x7fffe7086700 (LWP 18477)]
[New Thread 0x7fffd6de7700 (LWP 18478)]
[New Thread 0x7fffd65e6700 (LWP 18479)]
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000426, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000469, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000421, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000417, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000415, Avg Recall: -nan,  count: 0
Region Avg IOU: 0.605891, Class: 1.000000, Obj: 0.000000, No Obj: 0.000424, Avg Recall: 1.000000,  count: 1
Region Avg IOU: 0.519688, Class: 1.000000, Obj: 0.000000, No Obj: 0.000462, Avg Recall: 1.000000,  count: 1

Program received signal SIGSEGV, Segmentation fault.
0x000000000046ac60 in get_region_box (x=0xc84b440, biases=0x8d1400, n=0, index=-2014970546, i=18999980, j=18999980, 
    w=19, h=19, stride=361) at ./src/region_layer.c:79
79	    b.x = (i + x[index + 0*stride]) / w;

(gdb) where
#0  0x000000000046ac60 in get_region_box (x=0xc84b440, biases=0x8d1400, n=0, index=-2014970546, i=18999980, j=18999980, 
    w=19, h=19, stride=361) at ./src/region_layer.c:79
#1  0x000000000046bf8b in forward_region_layer (l=..., net=...) at ./src/region_layer.c:274
#2  0x000000000046d6e4 in forward_region_layer_gpu (l=..., net=...) at ./src/region_layer.c:556
#3  0x000000000047bc99 in forward_network_gpu (net=...) at ./src/network_kernels.cu:47
#4  0x000000000047c193 in train_network_datum_gpu (net=...) at ./src/network_kernels.cu:126
#5  0x0000000000452312 in train_network_datum (net=...) at ./src/network.c:264
#6  0x00000000004525e8 in train_network (net=..., d=...) at ./src/network.c:299
#7  0x000000000041d6e6 in train_detector (datacfg=0x7fffffffe498 "cfg/voc.data", 
    cfgfile=0x7fffffffe4a5 "cfg/tiny-yolo-voc.cfg", weightfile=0x7fffffffe4bb "tiny-yolo-voc.weights", 
    gpus=0x7fffffffdfa4, ngpus=1, clear=0) at ./examples/detector.c:116
#8  0x000000000042126d in run_detector (argc=6, argv=0x7fffffffe198) at ./examples/detector.c:698
#9  0x0000000000426165 in main (argc=6, argv=0x7fffffffe198) at ./examples/darknet.c:438

I don't know why index is -2014970546? I guess that is out of range ,but I can't find the resolutions,can anybody help me ,thanks！

**Comment by jremillard** [comment]
See issue #122
