### ISSUE TITLE
Use Yolo as DLL and SO libraries

### ISSUE THREAD

**Issue by AneTrotro** [pjreddie/darknet#1860]
Hi, anyone tried to use the darknet.py file to execute Yolo ?

I first compile the DLL thanks to the .sln files. But I got an error at the first DLL loaded : 
YOLO\darknet> python3 .\darknet.py
Traceback (most recent call last):
  File ".\darknet.py", line 115, in <module>
    print("Notice: CPU-only mode")
  File "C:\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] specified module could not be found

The first one is 'yolo_cpp_dll.dll', and it is right there in my folder when I run this command. If not, it raise the error 'NO DLL'.
So I do not get it why I have this error, do you know if this DLL has other dependecies which could be missing here ?

Thank you for your answer

**Comment by Aleksei91** [comment]
Use dependency walker tool to find dependencies on Windows.
Use ldd command in Linux

**Comment by AneTrotro** [comment]
Thanks for your answer, I tried to open my yolo_cpp_dll.dll in walker tool and  I got this error : 
Error: At least one file was not a 32-bit or 64-bit Windows module.

Do you think that the .sln did not generate well the dll ?
