### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by Krprashant94** [pjreddie/darknet#2011]
on TensorFlow 2.0

```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\tmp\yolo_test.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Program Files\Python37\lib\site-packages\darkflow\net\build.py", line 5, in <module>
    from .ops import op_create, identity
  File "C:\Program Files\Python37\lib\site-packages\darkflow\net\ops\__init__.py", line 1, in <module>
    from .simple import *
  File "C:\Program Files\Python37\lib\site-packages\darkflow\net\ops\simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by nakulrtm** [comment]
I am also facing the same error, please suggest the way out

**Comment by claessenskris** [comment]
Is there already a solution available other the downgrading to Tensorflow 1.14 ? Should be compatible with Tensorflow 2.x, no ?

**Comment by EddyKuo** [comment]
still no answer........

**Comment by nakulrtm** [comment]
No other solution, apologies for replying late.


*Nakul Surana*
Mobile: +91-8604295936  <+91-8604295936>
Email: nakulrtm@gmail.com | nakuls@iitk.ac.in
<http://facebook.com/nakulrtm>   <http://in.linkedin.com/in/nakulrtm>

If you Quit today, then from tomorrow quitting will be the easiest job for
you

- Surana

**Comment by Krprashant94** [comment]
Therefore this is an compatibility issues. 
Please make it compatible for TF 2.x 🙏🙏
I look at internet, **contrib** is moved in another package in TF 2.x.
