### ISSUE TITLE
Seg Fault on Raspberry Pi (found on Pi3B+ and Pi4) -- gdb output to help you debug

### ISSUE THREAD

**Issue by MegaMosquito** [pjreddie/darknet#2069]
Host info (Pi4-4GB, running Raspbian 10, also reproduced on Pi3B+):

10.10.10.4:~/git/darknet $ cat /proc/cpuinfo | grep Model
Model		: Raspberry Pi 4 Model B Rev 1.1
10.10.10.4:~/git/darknet $ cat /proc/meminfo | grep MemTotal
MemTotal:        3999800 kB
10.10.10.4:~/git/darknet $ uname -a
Linux 4b-4gb-rpi 4.19.80-v7l+ #1275 SMP Mon Oct 28 18:37:34 GMT 2019 armv7l GNU/Linux
10.10.10.4:~/git/darknet $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
10.10.10.4:~/git/darknet $ 

Steps to reproduce a seg fault:
  $  git clone https://github.com/pjreddie/darknet
  $  cd darknet
  $  make
  $  wget https://pjreddie.com/media/files/yolov3-tiny.weights
  $  cp ~/foo.jpeg .
  $  ./darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights foo.jpeg
  <seg fault>

GDB session showing the seg fault happening:

10.10.10.4:~/git/darknet $ gdb ./darknet
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./darknet...done.
/home/pi/git/darknet/detect: No such file or directory.
(gdb) 
(gdb) run detect cfg/yolov3-tiny.cfg yolov3-tiny.weights foo.jpeg
Starting program: /home/pi/git/darknet/darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights foo.jpeg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16  0.150 BFLOPs
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32  0.399 BFLOPs
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64  0.399 BFLOPs
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128  0.399 BFLOPs
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256  0.399 BFLOPs
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   13 conv    256  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 256  0.089 BFLOPs
   14 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   15 conv    255  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 255  0.044 BFLOPs
   16 yolo
   17 route  13
   18 conv    128  1 x 1 / 1    13 x  13 x 256   ->    13 x  13 x 128  0.011 BFLOPs
   19 upsample            2x    13 x  13 x 128   ->    26 x  26 x 128
   20 route  19 8
   21 conv    256  3 x 3 / 1    26 x  26 x 384   ->    26 x  26 x 256  1.196 BFLOPs
   22 conv    255  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 255  0.088 BFLOPs
   23 yolo
Loading weights from yolov3-tiny.weights...Done!
foo.jpeg: Predicted in 43.290422 seconds.

Program received signal SIGSEGV, Segmentation fault.
0x00086c08 in get_yolo_detections (l=..., w=640, h=480, netw=416, neth=416, 
    thresh=0.5, map=0x0, relative=1, dets=0xa4f58) at ./src/yolo_layer.c:336
336	                dets[count].prob[j] = (prob > thresh) ? prob : 0;
(gdb) where
#0  0x00086c08 in get_yolo_detections (l=..., w=640, h=480, netw=416, 
    neth=416, thresh=0.5, map=0x0, relative=1, dets=0xa4f58)
    at ./src/yolo_layer.c:336
#1  0x0006abbc in fill_network_boxes (net=0x1bcc58, w=640, h=480, thresh=0.5, 
    hier=0.5, map=0x0, relative=1, dets=0xa4f58) at ./src/network.c:548
#2  0x0006ada0 in get_network_boxes (net=0x1bcc58, w=640, h=480, thresh=0.5, 
    hier=0.5, map=0x0, relative=1, num=0xbefff330) at ./src/network.c:565
#3  0x0002b634 in test_detector (datacfg=0x8e190 "cfg/coco.data", 
    cfgfile=0xbefff77b "cfg/yolov3-tiny.cfg", 
    weightfile=0xbefff78f "yolov3-tiny.weights", 
    filename=0xbefff7a3 "foo.jpeg", thresh=0.5, hier_thresh=0.5, outfile=0x0, 
    fullscreen=0) at ./examples/detector.c:600
#4  0x0003070c in main (argc=5, argv=0xbefff614) at ./examples/darknet.c:437
(gdb) 
(gdb) list 320
315	
316	int get_yolo_detections(layer l, int w, int h, int netw, int neth, float thresh, int *map, int relative, detection *dets)
317	{
318	    int i,j,n;
319	    float *predictions = l.output;
320	    if (l.batch == 2) avg_flipped_yolo(l);
321	    int count = 0;
322	    for (i = 0; i < l.w*l.h; ++i){
323	        int row = i / l.w;
324	        int col = i % l.w;
(gdb) 
(gdb) break 319
Breakpoint 1 at 0x868dc: file ./src/yolo_layer.c, line 319.
(gdb) run detect cfg/yolov3-tiny.cfg yolov3-tiny.weights foo.jpeg
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/pi/git/darknet/darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights foo.jpeg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16  0.150 BFLOPs
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32  0.399 BFLOPs
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64  0.399 BFLOPs
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128  0.399 BFLOPs
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256  0.399 BFLOPs
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   13 conv    256  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 256  0.089 BFLOPs
   14 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   15 conv    255  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 255  0.044 BFLOPs
   16 yolo
   17 route  13
   18 conv    128  1 x 1 / 1    13 x  13 x 256   ->    13 x  13 x 128  0.011 BFLOPs
   19 upsample            2x    13 x  13 x 128   ->    26 x  26 x 128
   20 route  19 8
   21 conv    256  3 x 3 / 1    26 x  26 x 384   ->    26 x  26 x 256  1.196 BFLOPs
   22 conv    255  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 255  0.088 BFLOPs
   23 yolo
Loading weights from yolov3-tiny.weights...Done!
foo.jpeg: Predicted in 43.414887 seconds.

Breakpoint 1, get_yolo_detections (l=..., w=640, h=480, netw=416, neth=416, 
    thresh=0.5, map=0x0, relative=1, dets=0xa4f58) at ./src/yolo_layer.c:319
319	    float *predictions = l.output;
(gdb) list
314	}
315	
316	int get_yolo_detections(layer l, int w, int h, int netw, int neth, float thresh, int *map, int relative, detection *dets)
317	{
318	    int i,j,n;
319	    float *predictions = l.output;
320	    if (l.batch == 2) avg_flipped_yolo(l);
321	    int count = 0;
322	    for (i = 0; i < l.w*l.h; ++i){
323	        int row = i / l.w;
(gdb) step
320	    if (l.batch == 2) avg_flipped_yolo(l);
(gdb) p predictions[0]
$12 = -nan(0x400000)
(gdb) continue
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00086c08 in get_yolo_detections (l=..., w=640, h=480, netw=416, neth=416, 
    thresh=0.5, map=0x0, relative=1, dets=0xa4f58) at ./src/yolo_layer.c:336
336	                dets[count].prob[j] = (prob > thresh) ? prob : 0;
(gdb) p prob
$13 = -nan(0x400000)
(gdb) 

Same thing happens with the example "dog.jpg" image:

10.10.10.4:~/git/darknet $ ./darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights data/dog.jpg
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16  0.150 BFLOPs
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32  0.399 BFLOPs
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64  0.399 BFLOPs
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128  0.399 BFLOPs
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256  0.399 BFLOPs
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   13 conv    256  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 256  0.089 BFLOPs
   14 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   15 conv    255  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 255  0.044 BFLOPs
   16 yolo
   17 route  13
   18 conv    128  1 x 1 / 1    13 x  13 x 256   ->    13 x  13 x 128  0.011 BFLOPs
   19 upsample            2x    13 x  13 x 128   ->    26 x  26 x 128
   20 route  19 8
   21 conv    256  3 x 3 / 1    26 x  26 x 384   ->    26 x  26 x 256  1.196 BFLOPs
   22 conv    255  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 255  0.088 BFLOPs
   23 yolo
Loading weights from yolov3-tiny.weights...Done!
data/dog.jpg: Predicted in 43.196572 seconds.
Segmentation fault
10.10.10.4:~/git/darknet $

**Comment by MegaMosquito** [comment]
I also verified this same setup works with the V2 tiny config and weights, os it's something related to the V3 tiny data causing the problem on ARM32.
