### ISSUE TITLE
AttributeError: function 'network_width' not found, while executing darknet.py

### ISSUE THREAD

**Issue by vineeth0911** [pjreddie/darknet#2109]
I tried to execute "build\darknet\x64\darknet.py" after compiling both gpu & nogpu dll files and renamed them.
I encountered the following error:

C:\darknet-master\build\darknet\x64>py darknet.py
Traceback (most recent call last):
File "darknet.py", line 130, in
lib.network_width.argtypes = [c_void_p]
File "C:\Users\CHEPURI VINEETH\AppData\Local\Programs\Python\Python37\lib\ctypes_init_.py", line 377, in getattr
func = self.getitem(name)
File "C:\Users\CHEPURI VINEETH\AppData\Local\Programs\Python\Python37\lib\ctypes_init_.py", line 382, in getitem
func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'network_width' not found

I am able to use darknet.exe fie and predict the objects, this issue is while using python files.
please help me to resolve this issue .!

**Comment by jacedang** [comment]
Did you fix it? I encountered same problem

**Comment by Mike66662** [comment]
http://apticirl.com/2Mqz
