### ISSUE TITLE
undefined symbol: cudaPeekAtLastError

### ISSUE THREAD

**Issue by AmierCheng** [pjreddie/darknet#2158]
os:ubuntu16.04
cudn:10.1
Traceback (most recent call last):
  File "darknetDemo.py", line 19, in <module>
    from darknetpy import Detector
  File "/usr/local/anaconda3/lib/python3.7/site-packages/darknetpy-4.1-py3.7-linux-x86_64.egg/darknetpy/__init__.py", line 1, in <module>
    from .darknetpy import *
ImportError: /usr/local/anaconda3/lib/python3.7/site-packages/darknetpy-4.1-py3.7-linux-x86_64.egg/darknetpy/darknetpy.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaPeekAtLastError

**Comment by jantman** [comment]
It looks to me like that issue is with https://github.com/danielgatis/darknetpy not darknet itself...
