### ISSUE TITLE
ArgumentError in darknet.py after fixing syntax error

### ISSUE THREAD

**Issue by njoye** [pjreddie/darknet#241]
running `python darknet.py` results in this error for me:
`Traceback (most recent call last):
  File "darknet.py", line 122, in <module>
    net = load_net("cfg/tiny-yolo.cfg", "tiny-yolo.weights", 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
`
Inbefore I fixed the path in line 35 (it didn't find `libdarknet.so`)  and added brackets to the `print` statement in line 125. These being the only changes, I wonder why ctypes throws a ArgumentError, when all the values are as they should be (and I didn't change them from the original source code). Is the wrapper actually working ? 

Python:
`Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.`

Makefile (only changed lines):
`GPU=1
CUDNN=1
OPENCV=1`

System:
Ubuntu 16.04 GNOME 3
Intel Core i7 5820K
Nvidia TITAN Xp 

All dependencies (CUDA, OPENCV, etc) work fine with other projects, so that shouldn't be the problem.

Please help?:)

**Comment by TheMikeyR** [comment]
I'm experiencing the same issue and updated all paths in the file. 
```
python/darknet.py
Traceback (most recent call last):
  File "python/darknet.py", line 65, in <module>
    net = load_net("/mypath/cfg/yolo.cfg", "/mypath/backup/yolo_50000.weights")
  File "python/darknet.py", line 28, in load_net
    return load_network(cfg, weights, 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

**Comment by tsycnh** [comment]
I am trying to use proverbot.py , also have this problem
`    net = load_net("/path/darknet/cfg/yolo-lines.cfg","/path/darknet/backup/yolo-lines_63000.weights", 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type`

**Comment by TheMikeyR** [comment]
I've managed to get detection by using this python wrapper instead https://github.com/digitalbrain79/pyyolo

**Comment by ashish1405** [comment]
the `<class 'TypeError'>` is due the passing of string from python to c/c++ lib. just add 'b' before your string like `load_net(b"/path/darknet/cfg/yolo-lines.cfg",b"/path/darknet/backup/yolo-lines_63000.weights", 0) `

For string variables use `bytes(str_variable, encoding='utf-8')`

**Comment by mousomer** [comment]
Following @ashish1405 - when calling the C functions from python3, add `encode('utf-8')`. E.g.:

` 
   net = load_net(net_filename.encode('utf-8'), weights_filename.encode('utf-8'), 0)
    meta = load_meta(meta_filename.encode('utf-8'))
    r = detect(net, meta, jpg_filename.encode('utf-8'))
`

**Comment by ashish1405** [comment]
@mousomer I'm not a python expert, but won't the string.encode('utf-8') convert the python string to python string('utf-8'). But the C functions require char array, so the conversion to bytes.

**Comment by mousomer** [comment]
@ashish1405 
Neither am I. But - look at:

> In [1]: 'fff'.encode('utf-8')
> Out[1]: b'fff'

So, the `encode()` string function does indeed convert to char array. In any case, the code above works for me (python 3.6)

**Comment by ashish1405** [comment]
oh yes, that's correct 👍 . Sometimes it is difficult to predict how python behaves :)

**Comment by mousomer** [comment]
There's actually a python doc about this:
[https://docs.python.org/3/howto/unicode.html#converting-to-bytes](python doc)

**Comment by shoaibmanifold** [comment]
@mousomer Converting to UTF-8 solves the problem for Python 3. Thanks.
(For Python 2, that's not required.)

**Comment by WaltPeter** [comment]
Hi, I change the line `net = load_net("cfg/yolov3-tiny.cfg", "yolov3-tiny.weights", 0)` to `net = load_net("cfg/yolov3-tiny.cfg".encode("utf-8"), "yolov3-tiny.weights".encode("utf-8"), 0)`. 
But, I faced the error as below: 
`OSError: exception: access violation writing 0x000000000022E800` _(0x[something somthing])_
or 
`OSError: exception: access violation reading 0x000000000022E800` _(0x[something somthing])_
Maybe this problem is because of my OS (Windows 7)?

**Comment by mousomer** [comment]
Probably it is.
On MS Windows I would expect it to work without re-encoding to UTF-8. If that doesn't help you try a different encoding.

**Comment by yeechongyeung** [comment]
> the `<class 'TypeError'>` is due the passing of string from python to c/c++ lib. just add 'b' before your string like `load_net(b"/path/darknet/cfg/yolo-lines.cfg",b"/path/darknet/backup/yolo-lines_63000.weights", 0) `
> 
> For string variables use `bytes(str_variable, encoding='utf-8')`

That can be solve the py3 problem.

**Comment by ThomasA** [comment]
@pjreddie wouldn't it be a good idea to implement the `bytes` conversion as a permanent fix of this problem and thus upgrade the Python module to Python 3. After all, Python 2.7 is not supported anymore. I can submit a pull request if you like.

**Comment by ZhihuiYangCS** [comment]
Is there a method to stop printing the net information like `layer     filters    size      input     output`? It's a little bit annoying.
