### ISSUE TITLE
Error parsing html cfg file !

### ISSUE THREAD

**Issue by abhishekk06** [pjreddie/darknet#2538]
Hi,

Does anyone know how to solve this?

Starting program: /home/mdl/azk6085/2022_work/DAMOV/workloads/Darknet/darknet detect /home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/cfg/resnet152.cfg /home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/weights/resnet152.weights /home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/data/dog.jpg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000045a2b5 in read_cfg (filename=0x7fffffffe21a "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/cfg/resnet152.cfg") at ./src/parser.c:794
794                     if(!read_option(line, current->options)){
(gdb) bt
#0  0x000000000045a2b5 in read_cfg (filename=0x7fffffffe21a "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/cfg/resnet152.cfg") at ./src/parser.c:794
#1  0x00000000004592e7 in parse_network_cfg (filename=0x7fffffffe21a "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/cfg/resnet152.cfg")
    at ./src/parser.c:636
#2  0x00000000004525cf in load_network (cfg=0x7fffffffe21a "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/cfg/resnet152.cfg",
    weights=0x7fffffffe261 "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/weights/resnet152.weights", clear=0) at ./src/network.c:53
#3  0x000000000041e445 in test_detector (datacfg=0x472a90 "cfg/coco.data",
    cfgfile=0x7fffffffe21a "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/cfg/resnet152.cfg",
    weightfile=0x7fffffffe261 "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/weights/resnet152.weights",
    filename=0x7fffffffe2b0 "/home/mdl/azk6085/2022_work/DAMOV/workloads//Darknet/data/dog.jpg", thresh=0.239999995, hier_thresh=0.5, outfile=0x0, fullscreen=0)
    at ./examples/detector.c:572
#4  0x0000000000425958 in main (argc=5, argv=0x7fffffffdea8) at ./examples/darknet.c:422

**Comment by abhishekk06** [comment]
I see it segfault for the very first line
