### ISSUE TITLE
AssertionError: Over-read bin/yolo-voc.weights

### ISSUE THREAD

**Issue by isaacdchan** [pjreddie/darknet#352]
Received this error while trying to load YOLOv2 weights. Assertion errors are a completely new thing for me.

```C:\Users\isaac\Documents\STEM\Self Driving League\darkflow>python flow --model cfg\yolo-voc.cfg --load bin/yolo-voc.weights

Parsing ./cfg/yolo-voc.cfg
Parsing cfg\yolo-voc.cfg
Loading bin/yolo-voc.weights ...
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\cli.py", line 22, in cliHandler
    tfnet = TFNet(FLAGS)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\dark\darknet.py", line 27, in __init__
    self.load_weights()
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\dark\darknet.py", line 82, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\utils\loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\utils\loader.py", line 19, in __init__
    self.load(*args)
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\utils\loader.py", line 70, in load
    val = walker.walk(new.wsize[par])
  File "C:\Users\isaac\Documents\STEM\Self Driving League\darkflow\darkflow\utils\loader.py", line 127, in walk
    'Over-read {}'.format(self.path)
AssertionError: Over-read bin/yolo-voc.weights

C:\Users\isaac\Documents\STEM\Self Driving League\darkflow>
C:\Users\isaac\Documents\STEM\Self Driving League\darkflow>```

**Comment by bhavindhedhi** [comment]
@isaacdchan did you solve the error, if yes then how? im facing the same issue!!
