### ISSUE TITLE
crash on training own VOC dataset

### ISSUE THREAD

**Issue by guangwei** [pjreddie/darknet#780]
always crash at "resize_convolutional_layer"

Reading symbols from darknet...done.

warning: exec file is newer than core file.
[New LWP 3204]
[New LWP 3207]
[New LWP 3205]
[New LWP 3206]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./darknet detector train diandu/diandu.data diandu/diandu-voc.cfg darknet53.con'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fefef182428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7ff00b628740 (LWP 3204))]
(gdb) where
#0  0x00007fefef182428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fefef18402a in __GI_abort () at abort.c:89
#2  0x00007fefef1c47ea in __libc_message (do_abort=2, fmt=fmt@entry=0x7fefef2dded8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fefef1cdc71 in malloc_printerr (ar_ptr=0x7fefef511b20 <main_arena>, ptr=<optimized out>, 
    str=0x7fefef2dac92 "corrupted double-linked list", action=3) at malloc.c:5006
#4  _int_free (av=0x7fefef511b20 <main_arena>, p=<optimized out>, have_lock=1) at malloc.c:4014
#5  0x00007fefef1d0350 in _int_realloc (av=av@entry=0x7fefef511b20 <main_arena>, oldp=oldp@entry=0x7fefd4130000, 
    oldsize=oldsize@entry=692240, nb=nb@entry=1183760) at malloc.c:4358
#6  0x00007fefef1d1839 in __GI___libc_realloc (oldmem=0x7fefd4130010, bytes=1183744) at malloc.c:3045
#7  0x000000000042bb86 in resize_convolutional_layer (l=0x7fff9a3f4190, w=17, h=17) at ./src/convolutional_layer.c:383
#8  0x0000000000461423 in resize_network (net=0x1969e40, w=17, h=17) at ./src/network.c:373
#9  0x000000000041ed6c in train_detector (datacfg=0x7fff9a3f60d2 "xxx/xxx.data", 
    cfgfile=0x7fff9a3f60e5 "xxx/xxx-voc.cfg", weightfile=0x7fff9a3f60fb "darknet53.conv.74", gpus=0x7fff9a3f5274, 
    ngpus=1, clear=0) at ./examples/detector.c:79
#10 0x0000000000422a5d in run_detector (argc=6, argv=0x7fff9a3f5468) at ./examples/detector.c:842
#11 0x0000000000426e66 in main (argc=6, argv=0x7fff9a3f5468) at ./examples/darknet.c:434

**Comment by guangwei** [comment]
don't crash any more after switch to
https://github.com/AlexeyAB/darknet
