### ISSUE TITLE
YOLOv3:segmentation fault

### ISSUE THREAD

**Issue by ysh329** [pjreddie/darknet#811]
I `git clone` master code but segmentation fault when YOLOv3 execution as below:

```shell
~/code/darknet_prej$ ./darknet detect YOLOv3_416/yolov3.cfg YOLOv3_416/yolov3.weights data/warship.jpg
Segmentation fault (core dumped)
```

**Comment by jinyu121** [comment]
Same on Rasberry Pi.

**Comment by ysh329** [comment]
really strange, may memory leak?

**Comment by jinyu121** [comment]
I think it is because array out of range. Details can be found here: https://github.com/pjreddie/darknet/issues/823

Any solutions may be?

**Comment by Jibin-John** [comment]
I got the error

pi@raspberrypi:~/YOLO/darknet $ ./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32  0.299 BFLOPs
    1 conv     64  3 x 3 / 2   416 x 416 x  32   ->   208 x 208 x  64  1.595 BFLOPs
    2 conv     32  1 x 1 / 1   208 x 208 x  64   ->   208 x 208 x  32  0.177 BFLOPs
    3 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64  1.595 BFLOPs
    4 res    1                 208 x 208 x  64   ->   208 x 208 x  64
    5 conv    128  3 x 3 / 2   208 x 208 x  64   ->   104 x 104 x 128  1.595 BFLOPs
    6 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64  0.177 BFLOPs
    7 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128  1.595 BFLOPs
    8 res    5                 104 x 104 x 128   ->   104 x 104 x 128
    9 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64  0.177 BFLOPs
   10 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128  1.595 BFLOPs
   11 res    8                 104 x 104 x 128   ->   104 x 104 x 128
   12 conv    256  3 x 3 / 2   104 x 104 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   13 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   14 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   15 res   12                  52 x  52 x 256   ->    52 x  52 x 256
   16 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   17 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   18 res   15                  52 x  52 x 256   ->    52 x  52 x 256
   19 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   20 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   21 res   18                  52 x  52 x 256   ->    52 x  52 x 256
   22 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   23 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   24 res   21                  52 x  52 x 256   ->    52 x  52 x 256
   25 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   26 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   27 res   24                  52 x  52 x 256   ->    52 x  52 x 256
   28 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   29 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   30 res   27                  52 x  52 x 256   ->    52 x  52 x 256
   31 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   32 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   33 res   30                  52 x  52 x 256   ->    52 x  52 x 256
   34 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
   35 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
   36 res   33                  52 x  52 x 256   ->    52 x  52 x 256
   37 conv    512  3 x 3 / 2    52 x  52 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   38 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   39 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   40 res   37                  26 x  26 x 512   ->    26 x  26 x 512
   41 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   42 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   43 res   40                  26 x  26 x 512   ->    26 x  26 x 512
   44 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   45 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   46 res   43                  26 x  26 x 512   ->    26 x  26 x 512
   47 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   48 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   49 res   46                  26 x  26 x 512   ->    26 x  26 x 512
   50 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   51 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   52 res   49                  26 x  26 x 512   ->    26 x  26 x 512
   53 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   54 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   55 res   52                  26 x  26 x 512   ->    26 x  26 x 512
   56 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   57 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   58 res   55                  26 x  26 x 512   ->    26 x  26 x 512
   59 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256  0.177 BFLOPs
   60 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512  1.595 BFLOPs
   61 res   58                  26 x  26 x 512   ->    26 x  26 x 512
   62 conv   1024  3 x 3 / 2    26 x  26 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   63 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512  0.177 BFLOPs
   64 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   65 res   62                  13 x  13 x1024   ->    13 x  13 x1024
   66 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512  0.177 BFLOPs
   67 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   68 res   65                  13 x  13 x1024   ->    13 x  13 x1024
   69 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512  0.177 BFLOPs
   70 Segmentation fault

do you know how to fix this segmentation fault

**Comment by shartoo** [comment]
You  can clone another darkent [AlexeyAB darknet](https://github.com/AlexeyAB/darknet) ,thers is no segament error.

**Comment by bertalanimre** [comment]
I have something similar.

Works but gives wrong label:
```
bi@Nvidia-Learning ~/darknet $ ./darknet detect cfg/deer.cfg ../backup/deer_10000.weights ../trailcam_images/rYB688x3wvZtB2Y3GY5McKv25ip43Ms01NMgv5VG.jpeg
```

Doesn't work at all:
```
bi@Nvidia-Learning ~/darknet $ ./darknet detect cfg/deer.data cfg/deer.cfg ../backup/deer_10000.weights ../trailcam_images/rYB688x3wvZtB2Y3GY5McKv25ip43Ms01NMgv5VG.jpeg
Segmentation fault
```
For the second, there is no sign that it tries to do anything. I press enter for the command and I get the error message back straight. What gives?

**Comment by ysh329** [comment]
Is this issue about big-endian or little-endian?

**Comment by bertalanimre** [comment]
I'm back from a long holiday, sorry for not replying. Honestly I don't know what do you mean by bin/little endian. How do I find out and what other information would you require?

**Comment by karthickarima** [comment]
Segmentation fault
error like this any one give me solution for this 
~/darknet$ ./darknet detect cfg/yolov3.cfg yolov3.weights data/eagle.jpg -thresh 0
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128
.....
   34 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   35 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   36 res   33                  76 x  76 x 256   ->    76 x  76 x 256
   37 Segmentation fault (core dumped)

    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128

**Comment by jemeza** [comment]
Make sure that the .cfg file being passed in has the same network architecture as the architecture that was used to train the weights being passed in

**Comment by kkjhh0207** [comment]
The problem (segmentation fault) is far from the cfg modification because when u have wrong values in .cfg, usually the error message would be like this=> " check_error: Assertion `0' failed"
 
In my case(same problem related to segmentation fault) I found the problem came from the wrong labeling data. Check if u have any labeling data with zero coordinates and remove it
ex) 0 0.00 0.00 0.00 0.00
After removing this data, No more segmentation error appears.

**Comment by Zeaver** [comment]
> You can clone another darkent [AlexeyAB darknet](https://github.com/AlexeyAB/darknet) ,thers is no segament error.

that‘s amazing, thanks for ur answer!

**Comment by ahedmafarjeh** [comment]
> > You can clone another darkent [AlexeyAB darknet](https://github.com/AlexeyAB/darknet) ,thers is no segament error.
> 
> that‘s amazing, thanks for ur answer!

hello
how you run it ?
i run this : ./darknet.py detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
but i have this error 
![image](https://user-images.githubusercontent.com/91636357/153016987-27e8aa0c-5dd8-4501-af66-a16914347600.png)

Traceback (most recent call last):
  File "/home/pi/darknet/./darknet.py", line 236, in <module>
    lib = CDLL(cwd + "/libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pi/darknet/./libdarknet.so: cannot open shared object file: No such file or directory
can you help me , please>?!

**Comment by 7thstorm** [comment]
> > You can clone another darkent [AlexeyAB darknet](https://github.com/AlexeyAB/darknet) ,thers is no segament error.
> 
> that‘s amazing, thanks for ur answer!

Looks like the AlexeyAB repositiry is for yolo v4 and higher. How can I get v3?
