### ISSUE TITLE
OSError: dlopen(...) Image not found 

### ISSUE THREAD

**Issue by becca6223** [pjreddie/darknet#923]
OS: macOS 10.12

Hi, I am very new to yolo and trying to get the detected rectangles information (i.e coordinates, width, height). I found that there is a darknet.py. I was trying to run the file and see if I can get any information out of it. However i ran into this error:

![image](https://user-images.githubusercontent.com/14916327/42122344-2ff24ed4-7bf5-11e8-9362-037391b12660.png)

I tried to update the packages (billiard, celery, kombu, amqp) suggested from a post from stackoverflow (https://stackoverflow.com/questions/32905322/oserror-dlopenlibsystem-dylib-6-image-not-found) But still couldn't solve the issue. 

Has anyone ran into the same issue ?

**Comment by sharowyeh** [comment]
You have to use c compiler execute ` make` command with Makefile building libdarknet.so file, and place so file with your script working directory to load it.

**Comment by becca6223** [comment]
@sharowyeh thank you!

**Comment by zhangdm** [comment]
it still has problem.

Traceback (most recent call last):
  File "/Users/zhangx/darknet/python/darknet.py", line 48, in <module>
    lib = CDLL("libdarknet.so", RTLD_GLOBAL)
  File "/Users/zhangx/.conda/envs/lianghua/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libdarknet.so, 10): image not found
