### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by karanmartian** [pjreddie/darknet#928]
Hi,

Is there any way to write wrapper / API in python for yolo darknet? Basically I want to do things like object counting, updating a custom GUI with classes that are detected etc. by taking the output of YOLO.

**Comment by sharowyeh** [comment]
The python code which pjreddie provided works fine already, you can find them at [python folder](https://github.com/pjreddie/darknet/tree/master/python) and [detect file](https://github.com/pjreddie/darknet/blob/master/examples/detector.py) for prediction.
Or using [my fork](https://github.com/sharowyeh/darknet/tree/master-pjreddie/python) if implemented functions meet your requirement.

**Comment by karanmartian** [comment]
Thanks @sharowyeh but I am getting this error while executing:
I am running a miniconda python 3.6 with opencv 3.4.1
-----------------------------------------------
python detector-scipy-opencv.py
Traceback (most recent call last):
  File "detector-scipy-opencv.py", line 4, in <module>
    from darknet_libwrapper import *
  File "/home/karan/darknet/darknet_libwrapper.py", line 59, in <module>
    lib = ctypes.CDLL(lib_path, ctypes.RTLD_LOCAL)
  File "/home/karan/miniconda3/envs/tf/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libgdal.so.20: undefined symbol: sqlite3_column_table_name

**Comment by sharowyeh** [comment]
@karanmartian It only tested in Python2.7, and still working on fix issues from ctypes implementation in 3.6.

**Comment by karanmartian** [comment]
@sharowyeh fixed the error. Would you have any example for reading / performing detections on Video file?

**Comment by karanmartian** [comment]
I just wrote python code for video detections. but its kind of running slow. I was thinking of using this code instead in yolo_console_dll.cpp but getting this error. Have you encountered this before?

(tf) karan@karan-LinuxTP:~/al/darknet/src$ g++ yolo_console_dll.cpp
/tmp/cc4RfFu5.o: In function main': yolo_console_dll.cpp:(.text+0x60b): undefined reference toDetector::Detector(std::__cxx11::basic_string<char, std::char_traits, std::allocator >, std::__cxx11::basic_string<char, std::char_traits, std::allocator >, int)'
yolo_console_dll.cpp:(.text+0x734): undefined reference to Detector::load_image(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)' yolo_console_dll.cpp:(.text+0x77c): undefined reference toDetector::detect(image_t, float, bool)'
yolo_console_dll.cpp:(.text+0x79b): undefined reference to Detector::free_image(image_t)' yolo_console_dll.cpp:(.text+0x85b): undefined reference toDetector::~Detector()'
yolo_console_dll.cpp:(.text+0xad4): undefined reference to `Detector::~Detector()'
collect2: error: ld returned 1 exit status

**Comment by sharowyeh** [comment]
It is recommended that using [AlexeyAB's repository](https://github.com/AlexeyAB/darknet) for this c++ file modification.

**Comment by lakshpvt** [comment]
@karanmartian Could you share python code for video detection ??

**Comment by sharowyeh** [comment]
Updated in [my repo](https://github.com/sharowyeh/darknet/tree/master-pjreddie/python), quick represent video detection function with python code wrapped from libdarknet.so.

**Comment by deimsdeutsch** [comment]
@sharowyeh Getting compilation errors on your build. I suggest you take a look at them as some files are missing.

Project:
libdarknet.sln

**Comment by sharowyeh** [comment]
@deimsdeutsch Thank you for reminding me :)

And the issue feature of my project has been opened.

**Comment by shuoyuanxu** [comment]
Hi guys, 
I just tested the official python wrapper, I was wondering if it is normal for the python wrapper to be a little slower than the original code.

Mine GTX1050 gives me 0.08s for the dog demo on C++, and 0.106 for python

**Comment by vitovanjak** [comment]
@shuoyuanxu I have the same problem when I am running from terminal I get 60 FPS and when I am running from python I am getting 50 FPS which is a big difference if you scale it.

Can maybe someone explain why is this happening?

**Comment by vinnadipo09** [comment]
> ## Thanks @sharowyeh but I am getting this error while executing:
> I am running a miniconda python 3.6 with opencv 3.4.1
> python detector-scipy-opencv.py
> Traceback (most recent call last):
> File "detector-scipy-opencv.py", line 4, in 
> from darknet_libwrapper import *
> File "/home/karan/darknet/darknet_libwrapper.py", line 59, in 
> lib = ctypes.CDLL(lib_path, ctypes.RTLD_LOCAL)
> File "/home/karan/miniconda3/envs/tf/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: /usr/lib/libgdal.so.20: undefined symbol: sqlite3_column_table_name

Has anyone found a solution to this? I have been battling with the issue for quite some time.

**Comment by 18310837090** [comment]
> > ## Thanks @sharowyeh but I am getting this error while executing:
> > I am running a miniconda python 3.6 with opencv 3.4.1
> > python detector-scipy-opencv.py
> > Traceback (most recent call last):
> > File "detector-scipy-opencv.py", line 4, in
> > from darknet_libwrapper import *
> > File "/home/karan/darknet/darknet_libwrapper.py", line 59, in
> > lib = ctypes.CDLL(lib_path, ctypes.RTLD_LOCAL)
> > File "/home/karan/miniconda3/envs/tf/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > self._handle = _dlopen(self._name, mode)
> > OSError: /usr/lib/libgdal.so.20: undefined symbol: sqlite3_column_table_name
> 
> Has anyone found a solution to this? I have been battling with the issue for quite some time.


I also have this problem
